### ISSUE TITLE
front end list

### ISSUE THREAD

**Issue by ahmedtaaw** [ryanburgess/engineer-manager#6]
Thanks alot for the list, but i would like to ask you if you know a list like this but for front end development
:)

**Comment by ryanburgess** [comment]
I had started a list a long time ago: https://github.com/ryanburgess/learning-frontend-development

There are also a few lists out there:
https://gist.github.com/dypsilon/5819504
https://github.com/dypsilon/frontend-dev-bookmarks
https://github.com/dmytroyarmak/frontend-dev-resources
https://github.com/FrontendMasters/front-end-handbook
